image: Visual Studio 2017
init: 
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
version: $(package_version)-{build}
branches:
  only:
  - master
  - develop
  - alm
environment:
  nodejs_version: 8
install:
- ps: Install-Product node $env:nodejs_version
- cmd: npm install
cache: node_modules
build_script:
- cmd: npm run build
- cmd: npm run package:win
- cmd: signtool sign /v /f cert.pfx /t http://timestamp.verisign.com/scripts/timstamp.dll out\vr-viewer-win32-ia32\vr-viewer.exe
artifacts:
  - path: out/vr-viewer-win32-ia32
    name: vr-viewer
    type: zip