version: 0.0.{build}
branches:
  only:
  - master
  - develop
  - alm
environment:
  nodejs_version: 8
cache: node_modules
install:
- ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version 
- ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
- ps: Install-Product node $env:nodejs_version
- cmd: npm install
build_script:
- cmd: npm run build
- cmd: npm run package:win
- cmd: "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe" sign /v /f cert.pfx /t http://timestamp.verisign.com/scripts/timstamp.dll out\vr-viewer-win32-ia32\vr-viewer.exe
artifacts:
  - path: out/vr-viewer-win32-ia32
    name: vr-viewer
    type: zip